### ISSUE TITLE
Connect slide with video

### ISSUE THREAD

**Issue by AnifInnab** [LectCap/web_folder#5]
Some kind of Slide_video table is needed on the database to connect slides to videos. I will research more on how the slides are going to be uploaded. Picture by picture or some other more effective way, haven't really checked up the available options. Anyhow, please add some Slide_video table containing foreign keys of both video and slide on your databases.

**Comment by stmi11** [comment]
As far as I see it, this isn't relevant anymore and was implemented differently. Feel free to reopen if I'm wrong.
